import { blobToRawUrl } from "./github/url.js";
import { waitForFileView, mountIntoFileView, setNativeViewVisible, type Mounted } from "./github/mount.js";
import { JsonlStreamDecoder } from "./parser/jsonl-stream.js";
import { isMetaRecord, isMessageRecord, isSupportedSchemaVersion, type MetaRecord } from "./parser/schema.js";
import { renderRoot, type RootApi } from "./render/root.js";

type State = "init" | "loading" | "rendered" | "raw" | "degraded" | "error" | "disposed";

export class Controller {
  private state: State = "init";
  private abort = new AbortController();
  private mounted: Mounted | null = null;
  private api: RootApi | null = null;
  private readonly blobUrl: string;

  constructor(blobUrl: string) { this.blobUrl = blobUrl; }

  async run(): Promise<void> {
    this.state = "loading";
    const nativeView = await waitForFileView();
    if (this.state === "disposed") return;
    if (!nativeView) { this.state = "degraded"; return; }
    this.mounted = mountIntoFileView(nativeView);
    try {
      await this.fetchAndRender();
    } catch (e) {
      if (this.state === "disposed") return;
      if ((e as Error).name === "AbortError") return;
      console.error("[show-me-your-prompt]", e);
      this.state = "degraded";
      this.dispose();
    }
  }

  dispose(): void {
    if (this.state === "disposed") return;
    this.state = "disposed";
    this.abort.abort();
    this.mounted?.unmount();
    this.mounted = null;
  }

  private async fetchAndRender(): Promise<void> {
    const raw = blobToRawUrl(this.blobUrl);
    if (!raw) { this.dispose(); return; }
    let resp: Response;
    try {
      resp = await fetch(raw, { signal: this.abort.signal });
    } catch (e) {
      this.showFetchError();
      return;
    }
    if (resp.status === 403) { this.dispose(); return; }
    if (!resp.ok || !resp.body) { this.showDegraded(`HTTP ${resp.status}`); return; }

    const reader = resp.body.getReader();
    const dec = new JsonlStreamDecoder();
    let meta: MetaRecord | null = null;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      const records = dec.push(value);
      if (!this.consume(records, (m) => (meta = m))) return;
      if (!meta) continue;
    }
    const tail = dec.flush();
    this.consume(tail, (m) => (meta = m));

    if (!meta) {
      this.showDegraded("missing meta record");
    }
  }

  private consume(records: unknown[], onMeta: (m: MetaRecord) => void): boolean {
    for (const r of records) {
      if (isMetaRecord(r)) {
        if (!isSupportedSchemaVersion(r.schema_version)) {
          this.showUnsupportedVersion(r);
          return false;
        }
        if (!this.api) {
          this.api = renderRoot(r, { onToggleRendered: (on) => this.setRendered(on) });
          this.mounted!.container.appendChild(this.api.element);
          this.state = "rendered";
        }
        onMeta(r);
      } else if (isMessageRecord(r)) {
        this.api?.appendMessage(r);
      }
    }
    return true;
  }

  private setRendered(on: boolean): void {
    if (!this.api || !this.mounted) return;
    this.api.element.style.display = on ? "" : "none";
    setNativeViewVisible(this.mounted, !on);
    this.api.setMode(on ? "rendered" : "raw");
    this.state = on ? "rendered" : "raw";
  }

  private showFetchError(): void {
    if (!this.mounted) return;
    if (!this.api) {
      const fallbackMeta: MetaRecord = {
        type: "meta",
        schema_version: 1,
        source: "claude-code",
        exported_at: "",
        exported_by: "",
        title: ".prompttrace.jsonl",
        sanitization: { rules_applied: [], redaction_count: 0 },
      };
      this.api = renderRoot(fallbackMeta, { onToggleRendered: () => {} });
      this.mounted.container.appendChild(this.api.element);
    }
    this.api.showError("Failed to load .prompttrace.jsonl — network error", () => {
      this.abort = new AbortController();
      this.fetchAndRender().catch((e) => console.error(e));
    });
    this.state = "error";
  }

  private showUnsupportedVersion(r: MetaRecord): void {
    if (!this.mounted) return;
    this.api = renderRoot(
      { ...r, title: r.title },
      { onToggleRendered: () => {} },
    );
    this.mounted.container.appendChild(this.api.element);
    this.api.showWarning(
      `⚠ This file was generated by a newer prompttrace (schema_version ${r.schema_version}). Please upgrade the extension.`,
    );
    this.state = "degraded";
  }

  private showDegraded(reason: string): void {
    if (!this.mounted) return;
    if (!this.api) {
      const fallbackMeta: MetaRecord = {
        type: "meta",
        schema_version: 1,
        source: "claude-code",
        exported_at: "",
        exported_by: "",
        title: "Unrecognized .prompttrace.jsonl",
        sanitization: { rules_applied: [], redaction_count: 0 },
      };
      this.api = renderRoot(fallbackMeta, { onToggleRendered: () => {} });
      this.mounted.container.appendChild(this.api.element);
    }
    this.api.showWarning(`⚠ Unrecognized .prompttrace.jsonl format (${reason}). Falling back to raw view.`);
    setNativeViewVisible(this.mounted, true);
    this.state = "degraded";
  }
}
